# Generated by Django 3.0.7 on 2020-06-13 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=50, verbose_name='Project Name')),
            ],
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqnumber', models.CharField(max_length=15, verbose_name='REQ Number')),
                ('reqcreated', models.DateField(blank=True, default=None, null=True, verbose_name='REQ Created')),
                ('reqstatus', models.CharField(max_length=50, verbose_name='REQ Status')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('prnumber', models.CharField(max_length=20, verbose_name='PR Number')),
                ('ponumber', models.CharField(max_length=20, verbose_name='PO Number')),
                ('postatus', models.CharField(max_length=50, verbose_name='PO Status')),
                ('povendor', models.CharField(max_length=50, verbose_name='PO Vendor')),
                ('pomaterial', models.CharField(max_length=50, verbose_name='PO Material')),
                ('poprice', models.CharField(max_length=20, verbose_name='PO Price (USD)')),
                ('pocreated', models.DateField(blank=True, default=None, null=True, verbose_name='PO Created')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatable.Project')),
            ],
        ),
    ]
